version: "3.3"
services:
  postgres:
    image: rebecateodoro/postgres-resttest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resttest
    ports:
      - "5433:5433"
    build:
      context: .
    restart: always
    networks:
      - resttest-network     
  resttest:
    image: rebecateodoro/resttest
    restart: always
    build: .
    working_dir: /Resttest
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - resttest-network
    volumes:
      - ./resttest:/restest
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
networks:
    resttest-network:
        driver: bridge